In [1]:
L=[]
for i in range(2000,3201):
    if((i%7==0) and (i%5)):
        L.append(i)
print(L)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [4]:
def factorial(x):
    fact=1
    for i in range(2,x+1):
        fact*=i
    return fact
n=int(input("Enter the integer,please \n"))
print ("The factorial of",n,"is", factorial(n))

Enter the integer,please 
 8


The factorial of 8 is 40320


In [5]:
D={}
n=int(input("Enter the max number,please \n"))
for i in range (1,n+1):
    D[i]=i*i
print ("Here is the dictionnary containing integers between 1 and",n,"with their squares : ",D)

Enter the max number,please 
 10


Here is the dictionnary containing integers between 1 and 10 with their squares :  {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [9]:
def missing_char(chain,n):
    L=list(chain)
    del L[n]
    chain="".join(L)
    return chain
string=input("Enter the string,please\n")
i=int(input("Enter the index to remove,please\n"))
print("The new string :\n",missing_char(string,i))

Enter the string,please
 Tunisien
Enter the index to remove,please
 -1


The new string :
 Tunisie


In [6]:
import numpy as np
def Convert(array):
    L=[]
    for i in array:
        l=list(i)
        L.append(l)
    return(L)
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array)
print(Convert(array))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [13]:
import numpy as np
array1=np.array([0,1,2])
array2=np.array([2,1,0])
covariance=np.cov(array1,array2)
print("The coriance matrix of",array1,"and",array2,"is :\n",covariance)

The coriance matrix of [0 1 2] and [2 1 0] is :
 [[ 1. -1.]
 [-1.  1.]]


In [14]:
import math
C=50
H=30
D = input("Enter comma separated integers: ")
l1 = D.split (",")
l2 = []
for i in l1:
	l2.append(int(i))
for i in l2:
    Value=int(math.sqrt((2*C*i)/H))
    print(Value,end=',')

Enter comma separated integers:  100,150,180


18,22,24,